# Generated by Django 5.0.6 on 2024-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_delete_passwordresetrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
