# Generated by Django 5.0.6 on 2024-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("description", models.TextField(max_length=255)),
                ("patient_name", models.CharField(max_length=100)),
                ("patient_email", models.EmailField(max_length=100)),
                ("long_description", models.TextField()),
            ],
        ),
    ]
