# Generated by Django 5.0.6 on 2024-10-01 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("recipient", models.CharField(max_length=100)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("status", models.CharField(max_length=20)),
                (
                    "timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="timelines.timelines",
                    ),
                ),
            ],
        ),
    ]
