# Generated by Django 5.0.6 on 2024-10-01 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0002_timelinenotification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelinenotification",
            name="status",
        ),
    ]
