# Generated by Django 5.0.6 on 2024-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("heading", models.CharField(max_length=255)),
                ("spoons", models.CharField(max_length=10)),
                ("after_before", models.CharField(max_length=10)),
                ("am_pm", models.CharField(max_length=10)),
                ("days_left", models.CharField(max_length=10)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RefillRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("medication", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
