# Generated by Django 5.0.6 on 2024-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillrequest",
            name="medId",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refillrequest",
            name="patient_name",
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
