# Generated by Django 5.0.6 on 2024-07-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("emergency_contact_name", models.CharField(max_length=255)),
                ("emergency_contact_relationship", models.CharField(max_length=50)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("emergency_contact_email", models.EmailField(max_length=254)),
                ("current_health_conditions", models.TextField()),
                ("past_medical_history", models.TextField()),
                ("allergies", models.TextField()),
                ("current_medications", models.TextField()),
                ("primary_care_physician", models.CharField(max_length=255)),
                ("family_health_conditions", models.TextField()),
                ("lifestyle_habits", models.TextField()),
                ("exercise_routine", models.TextField()),
                ("dietary_habits", models.TextField()),
                ("insurance_provider", models.CharField(max_length=255)),
                ("policy_number", models.CharField(max_length=50)),
                ("insurance_phone", models.CharField(max_length=20)),
                ("consent_to_treat", models.BooleanField()),
                ("privacy_policy", models.BooleanField()),
                ("password", models.CharField(max_length=255)),
                ("enable_2fa", models.BooleanField()),
            ],
        ),
    ]
