# Generated by Django 5.0.6 on 2024-07-29 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="consent_to_treat",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="enable_2fa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_phone",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator("^\\d{10}$")],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="policy_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="privacy_policy",
            field=models.BooleanField(default=False),
        ),
    ]
