# Generated by Django 5.0.6 on 2024-07-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patient_last_login_alter_patient_consent_to_treat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
