# Generated by Django 5.0.6 on 2024-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_patient_otp_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="otp_secret",
        ),
        migrations.AddField(
            model_name="patient",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
