# Generated by Django 5.0.6 on 2024-10-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_patient_groups_patient_is_active_patient_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_phone",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
