# Generated by Django 5.0.6 on 2024-10-14 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0009_alter_patient_emergency_contact_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="dietary_habits",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="exercise_routine",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="insurance_phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="insurance_provider",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="lifestyle_habits",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="policy_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="primary_care_physician",
        ),
    ]
