# Generated by Django 5.0.6 on 2024-08-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("note", models.TextField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
