# Generated by Django 5.0.6 on 2024-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_part", models.CharField(max_length=100)),
                ("symptom", models.TextField()),
                ("date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
