# Generated by Django 5.0.6 on 2024-10-09 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("healthIssues", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalissue",
            old_name="body_part",
            new_name="bodyPart",
        ),
    ]
