# Generated by Django 5.0.6 on 2024-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthIssues", "0003_medicalissue_bloodpressure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalissue",
            name="health_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
