# Generated by Django 5.0.6 on 2024-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthIssues", "0004_medicalissue_health_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalissue",
            name="image",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
