import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen w-screen items-center justify-center">
      <div className="flex h-full w-full">
        <div className="h-full w-2/5"></div>
        <div className="h-full w-3/5">{children}</div>
      </div>
    </main>
  );
}
