# Generated by Django 5.0.6 on 2024-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=100)),
                ("speciality", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Afternoon", "Afternoon"),
                            ("Evening", "Evening"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Consultation"),
                            ("inPerson", "In-person Consultation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("problem_description", models.TextField()),
                ("patient_name", models.CharField(max_length=100)),
                ("patient_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
