# Generated by Django 5.0.6 on 2024-08-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookAppointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor_image",
            field=models.CharField(default="null", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient_email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
