# Generated by Django 5.0.6 on 2024-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookAppointments",
            "0004_notification_appointment_notification_is_sent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
