# Generated by Django 5.0.6 on 2024-10-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookAppointments", "0005_notification_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="phonenumber",
            field=models.CharField(default="", max_length=15),
        ),
    ]
